const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const percent=n=>(100*n).toFixed(1)+'%';
const pageURL=e=>e.url+'#page='+e.page;
function excerpt(text){let t=text.replace(/\s+/g,' ').trim();const data=t.indexOf('[데이터 원천]');if(data>=0)t=t.slice(data);else{t=t.replace(/^ESG 이해.*?부록\s*/,'').replace(/^심화 진단 항목 정의서\s*/,'').replace(/^추가 설명\s*/,'');}return t.slice(0,140)}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});if(!r.ok)throw new Error((await r.json()).error||'HTTP '+r.status);return r.json()}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');if(b.dataset.view==='evaluation')loadEvaluation()}));
document.querySelectorAll('[data-question]').forEach(b=>b.addEventListener('click',()=>{$('#question').value=b.dataset.question;if(b.dataset.language)$('#language').value=b.dataset.language;if(b.textContent.includes('도루코 포장'))$('#doc-id').value='dorco_profile';else if(b.textContent.includes('Working'))$('#doc-id').value='kesg_supply';else $('#doc-id').value='';$('#question').focus()}));
function renderEvidence(list){$('#evidence-count').textContent=list.length+' SOURCES';$('#evidence').innerHTML=list.length?list.map((e,i)=>`<article class="evidence-card"><div class="evidence-top"><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="kind">${e.doc_id==='dorco_profile'?'회사 공개 방향':'일반 ESG 지침'}</span><span class="page">PDF p.${e.page}</span></div><h3>${escape(e.title)}</h3><p>${escape(excerpt(e.text))}…</p><a href="${escape(pageURL(e))}" target="_blank" rel="noopener">원문 페이지 열기 ↗</a></article>`).join(''):'<div class="evidence-empty"><span>↗</span><h2>이 질문에는 근거가 없습니다.</h2><p>공개 문서 범위를 벗어난 내부 사실은<br>응답을 보류합니다.</p></div>'}
async function run(answer){const buttons=[...document.querySelectorAll('#query button,#query textarea,#query select')];buttons.forEach(b=>b.disabled=true);$('#progress').className='progress busy';$('#progress').textContent=answer?'문서를 검색하고 로컬 Qwen이 답변을 작성합니다. CPU 생성에는 시간이 걸릴 수 있습니다.':'다국어 문서 조각을 검색하고 있습니다.';try{const r=await api(answer?'/api/answer':'/api/search',{question:$('#question').value.trim(),method:$('#method').value,language:$('#language').value,doc_id:$('#doc-id').value||null,top_k:3});renderEvidence(r.evidence);if(answer){const status={generated:'GROUNDED ANSWER',abstained:'응답 보류 · 공개 자료 범위',failed:'생성 실패 · 근거만 표시'}[r.status];$('#answer').innerHTML=`<div class="section-label">${status}<span>${r.status==='generated'?'Qwen2.5 · 실제 생성':'상태 확인'}</span></div><p style="margin-top:14px">${escape(r.answer||'모델 답변 형식 검증을 통과하지 못했습니다. 오른쪽의 원문 근거를 확인해 주세요.')}</p>${(r.citations||[]).map(c=>`<a class="citation-badge" href="${escape(pageURL(c))}" target="_blank" rel="noopener">${c.doc_id==='dorco_profile'?'DORCO':'K-ESG'} · p.${c.page} ↗</a>`).join('')}<div class="answer-meta"><span>검색 ${r.retrieval_ms} ms</span><span>생성 ${(r.generation_ms/1000).toFixed(1)} s</span><span>${r.status==='generated'?'인용 ID 검사 완료':'명시적 상태 반환'}</span></div><div class="warning-note">${r.status==='generated'?'인용 ID 검사는 의미의 정확성을 보장하지 않습니다. 원문 확인이 필요합니다.':r.status==='abstained'?'비공개 질문 패턴을 차단한 결과입니다. 학습 기반의 관련성 판정은 아닙니다.':''}</div>`;$('#progress').textContent=r.status==='generated'?'검색된 근거로 생성한 답변입니다. 링크에서 원문을 확인하세요.':r.status==='abstained'?'공개 문서로 확인할 수 없는 질문에 답변을 보류했습니다.':'생성 실패를 숨기지 않고 근거를 표시합니다.'}else{$('#progress').textContent=`실제 ${r.method} 검색 · ${r.elapsed_ms} ms · 상위 ${r.evidence.length}개 근거`;$('#answer').innerHTML='<div class="section-label">RETRIEVAL COMPLETE</div><h2>관련 페이지를 찾았습니다.</h2><p>오른쪽에서 검색 순위와 원문을 확인하거나, “근거로 답변”을 눌러 모델 생성을 실행하세요.</p>'}}catch(e){$('#progress').textContent='실행 오류: '+e.message;$('#progress').className='progress error'}finally{buttons.forEach(b=>b.disabled=false);$('#progress').classList.remove('busy')}}
$('#answer-button').addEventListener('click',()=>run(true));$('#search-button').addEventListener('click',()=>run(false));
async function loadStatus(){try{const s=await api('/api/status');$('#health').textContent=s.ready?`${s.corpus.total_pages}쪽 · ${s.corpus.total_chunks}개 조각 · 인덱스 준비`:'인덱스 준비 중';$('#corpus-content').innerHTML=s.corpus.documents.map((d,i)=>`<article class="document-row"><div class="doc-number">0${i+1}</div><div><h2>${escape(d.title)}</h2><p>${d.id==='dorco_profile'?'회사 공개 방향 · 친환경 포장·소재 및 ESG 약속':'공급망 ESG 진단 항목 · 데이터 원천·기간·범위'}</p><a href="${escape(d.url)}" target="_blank" rel="noopener">공개 원문 PDF ↗</a></div><div><div class="doc-stats">${d.pages}<span>쪽 / ${d.chunks}개 조각</span></div><div class="doc-hash">SHA256 ${escape(d.sha256.slice(0,16))}…</div></div></article>`).join('')+`<div class="index-flow"><div class="index-stage"><small>01 / EXTRACT</small><h3>PDF 페이지 추출</h3><p>PyMuPDF<br>문서 ID·쪽 번호 보존</p></div><div class="index-stage"><small>02 / CHUNK</small><h3>겹치는 문서 조각</h3><p>900자 · 180자 중첩<br>PDF 특수 공백 정규화</p></div><div class="index-stage"><small>03 / EMBED</small><h3>다국어 E5 임베딩</h3><p>${s.embedding.dimension}차원 · 정규화<br>query / passage 접두어</p></div><div class="index-stage"><small>04 / RETRIEVE</small><h3>Dense + BM25</h3><p>코사인 유사도<br>RRF 순위 결합</p></div><div class="index-stage"><small>05 / GENERATE</small><h3>Qwen 근거 답변</h3><p>검색된 상위 3개 조각<br>인용 ID 검사·원문 링크</p></div></div><div class="model-line">Embedding: ${escape(s.embedding.id)} · revision ${escape(s.embedding.revision.slice(0,12))} · 최대 512 tokens<br>Generator: ${escape(s.generator.id)} · 로컬 CPU · ${s.generator.ready?'모델 준비 완료':'모델 준비 중'}<br>원문 PDF와 벡터 인덱스는 로컬에 보관합니다. 공개 저장소에서는 출처·해시·재구축 절차를 제공합니다.</div>`}catch(e){$('#health').textContent='서비스 연결 확인 필요'}}
async function loadEvaluation(){try{const e=await api('/api/evaluation');if(!e.methods){$('#evaluation-content').textContent='평가를 실행한 뒤 결과를 표시합니다.';return}const n=e.methods.hybrid.test.n;const failures=e.results.filter(r=>r.split==='test'&&r.method==='hybrid'&&(!r.first_relevant_rank||r.first_relevant_rank>5));$('#evaluation-content').innerHTML=`<div class="eval-heading"><div><h2>같은 질문, 세 가지 검색 방식.</h2><p>같은 검색 설정에서 v2 페이지 정답으로 다시 집계했습니다.<br>정답은 최초 평가 후 기초·심화 중복 페이지를 원문 대조해 보완했습니다.</p></div><div class="eval-count">${n}<small>TEST · 답변 가능 질문</small></div></div><table class="metrics-table"><thead><tr><th>SEARCH METHOD</th><th>Page Hit@1</th><th>Page Hit@5</th><th>MRR@5</th></tr></thead><tbody>${['bm25','dense','hybrid'].map(m=>{const r=e.methods[m].test;return `<tr class="${m==='dense'?'highlight':''}"><td>${{bm25:'BM25 · 단어 기반',dense:'Dense · 다국어 E5',hybrid:'Hybrid · RRF 결합'}[m]}</td><td><strong>${percent(r.page_hit_at_1)}</strong></td><td><strong>${percent(r.page_hit_at_5)}</strong><div class="metric-bar"><i style="width:${r.page_hit_at_5*100}%"></i></div></td><td>${r.mrr.toFixed(3)}</td></tr>`}).join('')}</tbody></table><div class="eval-bottom"><div><div class="section-label">HYBRID · TOP 5 실패 사례 <span>${failures.length} / ${n}</span></div>${failures.slice(0,4).map(r=>`<div class="case-row"><span>${escape(r.id)} · ${escape(r.language.toUpperCase())} · 정답 p.${r.expected_pages.join(', ')}</span><b>${r.first_relevant_rank?'검색 순위 '+r.first_relevant_rank:'정답 페이지 미검색'}</b></div>`).join('')||'<p>해당 자체 세트에서 Top 5 실패가 없었습니다.</p>'}</div><div class="eval-note">Page Hit@k: 상위 k개 조각에 정답 문서·페이지가 포함된 질문 비율.<br>MRR@5: 상위 5개에서 최초 정답 조각의 역순위 평균. 미검색은 0.<br><b>이 결과는 실제 협력사 업무나 LLM 답변 정확도의 평가가 아닙니다.</b> 비공개 질문의 응답 보류는 별도 패턴 가드로 검사합니다.</div></div>`}catch(e){$('#evaluation-content').textContent='평가 결과를 불러오지 못했습니다: '+e.message}}
loadStatus();


